# Generated by Django 3.1.4 on 2020-12-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Лейбл', 'verbose_name_plural': 'Лейблы'},
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=200, verbose_name='Расходы')),
                ('categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category', verbose_name='Категории')),
                ('labels_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.label', verbose_name='Лейблы')),
            ],
            options={
                'verbose_name': 'Количество',
                'verbose_name_plural': 'Количество',
            },
        ),
    ]
