# Generated by Django 3.1.4 on 2020-12-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20201213_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.IntegerField(verbose_name='Расходы'),
        ),
    ]
