# Generated by Django 3.1.4 on 2020-12-16 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0004_amount_date_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='date_add',
            new_name='add_date',
        ),
        migrations.RenameField(
            model_name='amount',
            old_name='categories_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='amount',
            old_name='labels_id',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='categories_id',
            new_name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to=settings.AUTH_USER_MODEL),
        ),
    ]
